### PR TITLE
DC hex logo for stickers

### PR DESCRIPTION
**Pull request by noamross**
I made this for a [personal project](https://twitter.com/Voovarb/status/679859794719592449). Thought it might be useful in case DC decides to make some hex stickers.

### CODE REVIEW

**Comment by tracykteal** [comment]
Thanks so much @noamross! This is great. We've really been wanting a hex version. Also that blanket is  ridiculously awesome! I think you might have a side career in the works. 

Would it be OK if we put it up on StickerMule and had some made to distribute?

**Comment by noamross** [comment]
Please do!  Let me know when they're on StickerMule. I'll also submit this to http://hexb.in/

**Comment by gvwilson** [comment]
Please poke me about StickerMule as well - @jduckles will want to get swag.

**Comment by tracykteal** [comment]
Thanks! We'll probably try a couple different background colors. It looks like that's pretty easy to change with an svg file, yes?

**Pull request merged**
